### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by joaquinpereyra** [ucudal/pii_2019_equipo4#20]
![image](https://user-images.githubusercontent.com/42189479/59162301-efa06480-8ac4-11e9-96d7-612bd1df6733.png)

**Comment by perez5010** [comment]
Quedo resuelto

**Comment by joaquinpereyra** [comment]
Solucionado, no se habia inyectado correctamente en _loginPartial [Proyecto/src/Pages/Shared/_LoginPartial.cshtml](url)
